version : '3'

services :
  web:
      image: nginx
      volumes:
            - ./src/main/resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
  db:
    image: mysql:5.7

    ports:
      - "3306:3306"

    environment:
           MYSQL_ROOT_PASSWORD: sepomex
           MYSQL_DATABASE: sepomex
           MYSQL_USER: sepomex
           MYSQL_PASSWORD: sepomex

  app:
    depends_on:
      - web
      - db
    image: sepomex