version : '3'

services :
  web:
      image: nginx
      volumes:
            - ./src/main/resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
  db:
    image: jesusperales/sepomex-db-postgresql
    ports:
      - "5432:5432"

  app:
    ports:
      - "8080:8007"
    depends_on:
      - web
      - db
    image: jesusperales/sepomex-api:latest
    volumes:
      - app-data:/sepomex-indices

volumes:
  db-data:
  app-data:
