version : '3'

services :
  web:
      image: nginx
      volumes:
            - ./src/main/resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
  db:
    image: jesusperales/sepomex-db-postgresql
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"

  app:
    ports:
      - "8080:8007"
    depends_on:
      - web
      - db
    image: jesusperales/sepomex-api:latest
    volumes:
      - app-data:/sepomex-indices
    networks:
      - default


volumes:
  db-data:
  app-data:

networks:
  default:
    external:
      name: wso2
