version : '3'

services :
  web:
      image: nginx
      volumes:
            - ./src/main/resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
  db:
    image: mysql:8.0.3
    volumes:
           - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

    environment:
           MYSQL_ROOT_PASSWORD: sepomex
           MYSQL_DATABASE: sepomex
           MYSQL_USER: sepomex
           MYSQL_PASSWORD: sepomex

  app:
    ports:
      - "8080:8080"
    depends_on:
      - web
      - db
    image: sepomex:latest

    environment:
           JAVA_OPTS : -server -Xms2048m -Xmx6144m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

volumes:
  db-data:
