version : '3'

services :
  web:
      image: nginx
      volumes:
            - ./src/main/resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:
           POSTGRES_DB: sepomex
           POSTGRES_USER: sepomex
           POSTGRES_PASSWORD: sepomex

  app:
    ports:
      - "8080:8080"
    depends_on:
      - web
      - db
    image: sepomex:latest

volumes:
  db-data:
